### ISSUE TITLE
 saved pictures(frames) are all black when enable_output = true

### ISSUE THREAD

**Issue by fastcode3d** [A-Dying-Pig/OpenGL_NeuralTexture#4]
when i set enable_output = false,The screen can be displayed normally.
when i set enable_output = true,recompile and run the program. 
Uv and Camera extrinsics are saved correctly, but the screen and the saved pictures(frames) are all black.

Does anyone know the possible cause?

**Comment by genesis02** [comment]
Was it resolved..
